# Generated by Django 5.2.6 on 2025-09-09 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('category', models.CharField(choices=[('jersey', 'Jersey'), ('t-shirt', 'T-shirt'), ('pants', 'Pants'), ('socks', 'Socks'), ('shoes', 'Shoes'), ('goalkeeper glove', 'Goalkeeper Glove'), ('ball', 'Ball'), ('tumbler', 'Tumbler')], max_length=25)),
                ('is_featured', models.BooleanField(default=False)),
                ('product_views', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
